// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WorkflowSample.Service.Models.WorkflowEngineModels;
//
//    var engineQueryHistoricProcessInstanceGrid = EngineQueryHistoricProcessInstanceGrid.FromJson(jsonString);

namespace WorkflowSample.Service.Models.WorkflowEngineModels
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class EngineQueryHistoricProcessInstanceGrid:BaseWorkflowResponse
    {
        [JsonProperty("data")]
        public EngineQueryHistoricProcessInstance[] Data { get; set; }

        [JsonProperty("total")]
        public long Total { get; set; }

        [JsonProperty("start")]
        public long Start { get; set; }

        [JsonProperty("sort")]
        public string Sort { get; set; }

        [JsonProperty("order")]
        public string Order { get; set; }

        [JsonProperty("size")]
        public long Size { get; set; }
    }

    public partial class EngineQueryHistoricProcessInstance
    {
        [JsonProperty("id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Id { get; set; }

        [JsonProperty("businessKey")]
        public string BusinessKey { get; set; }

        [JsonProperty("processDefinitionId")]
        public string ProcessDefinitionId { get; set; }

        [JsonProperty("processDefinitionUrl")]
        public Uri ProcessDefinitionUrl { get; set; }

        [JsonProperty("startTime")]
        public string StartTime { get; set; }

        [JsonProperty("endTime")]
        public string EndTime { get; set; }

        [JsonProperty("durationInMillis")]
        public long DurationInMillis { get; set; }

        [JsonProperty("startUserId")]
        public string StartUserId { get; set; }

        [JsonProperty("startActivityId")]
        public string StartActivityId { get; set; }

        [JsonProperty("endActivityId")]
        public string EndActivityId { get; set; }

        [JsonProperty("deleteReason")]
        public object DeleteReason { get; set; }

        [JsonProperty("superProcessInstanceId")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long SuperProcessInstanceId { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("variables")]
        public Variable[] Variables { get; set; }

        [JsonProperty("tenantId")]
        public object TenantId { get; set; }
    }

  
}
