// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WorkflowSample.Service.Models.WorkflowEngineModels;
//
//    var engineActivateProcessDefinitionRequest = EngineActivateProcessDefinitionRequest.FromJson(jsonString);

namespace WorkflowSample.Service.Models.WorkflowEngineModels
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class EngineActivateProcessDefinitionRequest
    {
        [JsonProperty("processDefinitionKey")]
        public string ProcessDefinitionKey { get; set; }

        [JsonProperty("businessKey")]
        public string BusinessKey { get; set; }

        [JsonProperty("tenantId")]
        public string TenantId { get; set; }

        [JsonProperty("variables")]
        public Variable[] Variables { get; set; }
    }

    public partial class Variable
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("value")]
        public string Value { get; set; }

        [JsonProperty("scope")]
        public string Scope { get; set; }
        
        [JsonProperty("operation")]
        public string Operation { get; set; }

    }

    public partial class EngineActivateProcessDefinitionRequest
    {
        public static EngineActivateProcessDefinitionRequest FromJson(string json) => JsonConvert.DeserializeObject<EngineActivateProcessDefinitionRequest>(json, WorkflowSample.Service.Models.WorkflowEngineModels.Converter.Settings);
    }

    
}
