// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WorkflowSample.Service.Models.WorkflowEngineModels;
//
//    var engineTaskActionRequest = EngineTaskActionRequest.FromJson(jsonString);

namespace WorkflowSample.Service.Models.WorkflowEngineModels
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class EngineTaskActionRequest
    {
        [JsonProperty("action")]
        public string Action { get; set; }

        [JsonProperty("variables")]
        public object[] Variables { get; set; }

        [JsonProperty("assignee")]
        public string Assignee { get; set; }
    }

    public partial class EngineTaskActionRequest
    {
        public static EngineTaskActionRequest FromJson(string json) => JsonConvert.DeserializeObject<EngineTaskActionRequest>(json, WorkflowSample.Service.Models.WorkflowEngineModels.Converter.Settings);
    }

   
}