// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WorkflowSample.Service.Models.WorkflowEngineModels;
//
//    var engineTask = EngineTask.FromJson(jsonString);

namespace WorkflowSample.Service.Models.WorkflowEngineModels
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class EngineTask
    {
        [JsonProperty("assignee")]
        public string Assignee { get; set; }

        [JsonProperty("createTime")]
        public string CreateTime { get; set; }

        [JsonProperty("delegationState")]
        public string DelegationState { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("dueDate")]
        public string DueDate { get; set; }

        [JsonProperty("execution")]
        public Uri Execution { get; set; }

        [JsonProperty("id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("owner")]
        public string Owner { get; set; }

        [JsonProperty("parentTask")]
        public Uri ParentTask { get; set; }

        [JsonProperty("priority")]
        public long Priority { get; set; }

        [JsonProperty("processDefinition")]
        public Uri ProcessDefinition { get; set; }

        [JsonProperty("processInstance")]
        public Uri ProcessInstance { get; set; }

        [JsonProperty("suspended")]
        public bool Suspended { get; set; }

        [JsonProperty("taskDefinitionKey")]
        public string TaskDefinitionKey { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("tenantId")]
        public object TenantId { get; set; }
    }

    public partial class EngineTask
    {
        public static EngineTask FromJson(string json) => JsonConvert.DeserializeObject<EngineTask>(json, WorkflowSample.Service.Models.WorkflowEngineModels.Converter.Settings);
    }

  
}
