// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WorkflowSample.Service.Models.WorkflowEngineModels;
//
//    var queryHistoricProcessInstanceRequest = QueryHistoricProcessInstanceRequest.FromJson(jsonString);

using WorkflowSample.Service.Models.WorkflowEngineModels;

namespace WorkflowSample.Service.Models
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class QueryHistoricProcessInstanceRequest
    {
        public bool includeTaskLocalVariables = true;
        public bool includeProcessVariables = true;
        public string taskAssignee;
        public string taskAssigneeLike;
        public string taskInvolvedUser;
        public bool? finished;
        public bool? processFinished;
        public string taskName;
        public string taskNameLike;
        public string processDefinitionKey;

        [JsonProperty("processDefinitionId")] public string ProcessDefinitionId { get; set; }

        [JsonProperty("variables")] public Variable[] Variables { get; set; }
    }
}